### PR TITLE
Fix compatibility with league/oauth2-client and PHP 7.1

### LINKED ISSUE #13: Make package compatible with league/oauth2-client v2.0
Do you have plans on releasing a version compatible with `league/oauth2-client` v2.0

We have v2.0 included in our app because it's required by `league/oauth2-linkedin` and `league/oauth2-google.`

By looking at the change list https://github.com/thephpleague/oauth2-client/blob/master/CHANGELOG.md it seems like the only breaking change is "Rename `getResponse()` to `getParsedResponse()`" used in `Slack.fetchAuthorizedUserDetails`

### PR DESCRIPTION
**Pull request by pyrech**
Fix #13

### CODE REVIEW

**Comment by pyrech** [comment]
Travis fail to run the build for hhvm :disappointed: 

Do you really care about the compatibility with hhvm or should I remove it from the build matrix?

**Comment by pyrech** [comment]
Was easy to fix after all :smile:

**Comment by adam-paterson** [comment]
@pyrech Thanks for this, created release 1.1.3

**Comment by pyrech** [comment]
Awesome :tada: Thanks :)

**Pull request merged**
